<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_SCHEDULE A FREE DISCOVERY SESSION</name>
   <tag></tag>
   <elementGuidId>c2194b6f-50f3-4817-98a9-d12843d7cdcd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.et_pb_button.et_pb_button_1.et_pb_bg_layout_light</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//article[@id='post-217913']/div/div/div/div[4]/div[3]/div/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>76ed51e3-9319-42af-ba05-21abbebec2e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>et_pb_button et_pb_button_1 et_pb_bg_layout_light</value>
      <webElementGuid>12bdf5b3-8da9-45e6-8783-a92aec937e79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://forms.clickup.com/2314027/p/f/26ktb-6387/56LKNUZ9BDYXSC73SY/unlock-your-automation-potentialwitha-free-framework-assessment</value>
      <webElementGuid>45bbfe17-9535-4aa8-a578-656c84316833</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>bef8243a-a0da-43f4-ab3a-e26f3f362a4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SCHEDULE A FREE DISCOVERY SESSION</value>
      <webElementGuid>f08029f5-4b49-471f-8453-36b35dc44a4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post-217913&quot;)/div[@class=&quot;entry-content&quot;]/div[@class=&quot;et-l et-l--post&quot;]/div[@class=&quot;et_builder_inner_content et_pb_gutters2&quot;]/div[@class=&quot;et_pb_section et_pb_section_3 et_pb_with_background et_section_regular&quot;]/div[@class=&quot;et_pb_row et_pb_row_7&quot;]/div[@class=&quot;et_pb_column et_pb_column_4_4 et_pb_column_18  et_pb_css_mix_blend_mode_passthrough et-last-child&quot;]/div[@class=&quot;et_pb_button_module_wrapper et_pb_button_1_wrapper et_pb_button_alignment_center et_pb_module&quot;]/a[@class=&quot;et_pb_button et_pb_button_1 et_pb_bg_layout_light&quot;]</value>
      <webElementGuid>e81f3bd1-378e-4db3-8590-3a8126f91e06</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='post-217913']/div/div/div/div[4]/div[3]/div/div/a</value>
      <webElementGuid>103eccd4-e6a4-4f3e-b235-64a0246aa2e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'SCHEDULE A FREE DISCOVERY SESSION')])[2]</value>
      <webElementGuid>4ca64a49-bff6-4393-bc9f-5ca9c3ceef74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://forms.clickup.com/2314027/p/f/26ktb-6387/56LKNUZ9BDYXSC73SY/unlock-your-automation-potentialwitha-free-framework-assessment')])[4]</value>
      <webElementGuid>85a0fa5e-499f-4031-816e-21273dadfdc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/a</value>
      <webElementGuid>b4529f74-30b9-4d93-8e7e-dbb3655a0ad1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://forms.clickup.com/2314027/p/f/26ktb-6387/56LKNUZ9BDYXSC73SY/unlock-your-automation-potentialwitha-free-framework-assessment' and (text() = 'SCHEDULE A FREE DISCOVERY SESSION' or . = 'SCHEDULE A FREE DISCOVERY SESSION')]</value>
      <webElementGuid>381a116a-ad69-48c4-921e-52a9e53af0b4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
