<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Push Higher Quality Software To Market Faster</name>
   <tag></tag>
   <elementGuidId>7ae8f9c5-0c0d-4c3f-b7e8-c99ab53881a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h1.et_pb_module_heading</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//article[@id='post-217913']/div/div/div/div/div/div/div/div/h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>fb088b3c-3544-41d6-b792-407da6b313d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>et_pb_module_heading</value>
      <webElementGuid>26feebd8-a606-473f-82ee-e201262f3eed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Push Higher Quality Software To Market Faster</value>
      <webElementGuid>3e955f90-80d6-47ff-919f-65a5a9a4ecff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post-217913&quot;)/div[@class=&quot;entry-content&quot;]/div[@class=&quot;et-l et-l--post&quot;]/div[@class=&quot;et_builder_inner_content et_pb_gutters2&quot;]/div[@class=&quot;et_pb_section et_pb_section_0 et_pb_with_background et_section_regular&quot;]/div[@class=&quot;et_pb_row et_pb_row_0 et_pb_gutters1&quot;]/div[@class=&quot;et_pb_column et_pb_column_1_2 et_pb_column_0  et_pb_css_mix_blend_mode_passthrough&quot;]/div[@class=&quot;et_pb_module et_pb_heading et_pb_heading_0 et_pb_bg_layout_&quot;]/div[@class=&quot;et_pb_heading_container&quot;]/h1[@class=&quot;et_pb_module_heading&quot;]</value>
      <webElementGuid>2fee492d-6ea9-45b7-a2db-2bc3c0852a58</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='post-217913']/div/div/div/div/div/div/div/div/h1</value>
      <webElementGuid>d9d1501a-49ae-4702-93e4-99a2b796dd97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>16bebbb9-812a-4628-8ada-c4a0df46c1b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Push Higher Quality Software To Market Faster' or . = 'Push Higher Quality Software To Market Faster')]</value>
      <webElementGuid>74c1aa7f-1924-44d5-b329-52e747c2a4a6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
