<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Grow Your Teams And Your Customers Confidence In Your Software</name>
   <tag></tag>
   <elementGuidId>cf8741c4-9040-4437-9494-e42dd489af7b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.et_pb_module.et_pb_heading.et_pb_heading_4.et_pb_bg_layout_ > div.et_pb_heading_container > h2.et_pb_module_heading</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//article[@id='post-217913']/div/div/div/div[2]/div/div[2]/div/div/h2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>e27c9a13-3f4b-4f0f-972d-aca0eed60e97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>et_pb_module_heading</value>
      <webElementGuid>da2f6cb1-d65c-4a79-bf0f-9736cf7d4485</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Grow Your Team's And Your Customers' Confidence In Your Software</value>
      <webElementGuid>897a3c7d-4134-406a-a39b-94703cfd712c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post-217913&quot;)/div[@class=&quot;entry-content&quot;]/div[@class=&quot;et-l et-l--post&quot;]/div[@class=&quot;et_builder_inner_content et_pb_gutters2&quot;]/div[@class=&quot;et_pb_section et_pb_section_1 et_pb_with_background et_section_regular&quot;]/div[@class=&quot;et_pb_row et_pb_row_2 et_pb_gutters1&quot;]/div[@class=&quot;et_pb_column et_pb_column_1_2 et_pb_column_6  et_pb_css_mix_blend_mode_passthrough et-last-child&quot;]/div[@class=&quot;et_pb_module et_pb_heading et_pb_heading_4 et_pb_bg_layout_&quot;]/div[@class=&quot;et_pb_heading_container&quot;]/h2[@class=&quot;et_pb_module_heading&quot;]</value>
      <webElementGuid>b0f5d9d4-47ed-4f6d-86ed-3a4d38375a34</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='post-217913']/div/div/div/div[2]/div/div[2]/div/div/h2</value>
      <webElementGuid>0d579a00-e320-4cac-99c3-87808414d97d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/h2</value>
      <webElementGuid>b000938c-ff92-4a86-a6de-a10a6f3d6969</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = concat(&quot;Grow Your Team&quot; , &quot;'&quot; , &quot;s And Your Customers&quot; , &quot;'&quot; , &quot; Confidence In Your Software&quot;) or . = concat(&quot;Grow Your Team&quot; , &quot;'&quot; , &quot;s And Your Customers&quot; , &quot;'&quot; , &quot; Confidence In Your Software&quot;))]</value>
      <webElementGuid>027232cc-b1c7-4f9d-936f-81cbe8d27849</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
