<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Share_et_pb_scroll_top et-pb-icon et-visible</name>
   <tag></tag>
   <elementGuidId>a70a88b1-70a7-4552-ab22-20c0c4b83aba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.et_pb_scroll_top.et-pb-icon.et-visible</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>1a2347f5-7ebe-4ec8-ab1b-39585850abd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>et_pb_scroll_top et-pb-icon et-visible</value>
      <webElementGuid>3ece6cde-c646-44ec-b4eb-15380ef0198e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;js&quot;]/body[@class=&quot;home page-template-default page page-id-217913 et-tb-has-template et-tb-has-header et-tb-has-footer et_button_icon_visible et_button_custom_icon et_pb_button_helper_class et_cover_background et_pb_gutter et_pb_gutters2 et_pb_pagebuilder_layout et_no_sidebar et_divi_theme et-db chrome&quot;]/span[@class=&quot;et_pb_scroll_top et-pb-icon et-visible&quot;]</value>
      <webElementGuid>4ae54cb7-7356-45eb-8629-9a90dddea467</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//body/span</value>
      <webElementGuid>2b6f1174-fb1c-41b9-ad83-fc17e350c426</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
